# Generated by Django 5.1.1 on 2024-10-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
